<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="319" started-at="2017-07-25T17:26:43Z" finished-at="2017-07-25T17:26:43Z">
    <groups>
      <group name="Sanity">
        <method signature="Grouping.advancedSearch()[pri:3, instance:com.info.TestRunner.Grouping@3a8624]" name="advancedSearch" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.login()[pri:1, instance:com.info.TestRunner.Grouping@3a8624]" name="login" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.logout()[pri:10, instance:com.info.TestRunner.Grouping@3a8624]" name="logout" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.search()[pri:2, instance:com.info.TestRunner.Grouping@3a8624]" name="search" class="com.info.TestRunner.Grouping"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="Grouping.advancedSearch()[pri:3, instance:com.info.TestRunner.Grouping@3a8624]" name="advancedSearch" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.login()[pri:1, instance:com.info.TestRunner.Grouping@3a8624]" name="login" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.logout()[pri:10, instance:com.info.TestRunner.Grouping@3a8624]" name="logout" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.prepaidRecharge()[pri:5, instance:com.info.TestRunner.Grouping@3a8624]" name="prepaidRecharge" class="com.info.TestRunner.Grouping"/>
        <method signature="Grouping.billPayment()[pri:4, instance:com.info.TestRunner.Grouping@3a8624]" name="billPayment" class="com.info.TestRunner.Grouping"/>
      </group> <!-- Regression -->
    </groups>
    <test name="Default test" duration-ms="319" started-at="2017-07-25T17:26:43Z" finished-at="2017-07-25T17:26:43Z">
      <class name="com.info.TestRunner.Grouping">
        <test-method status="FAIL" signature="login()[pri:1, instance:com.info.TestRunner.Grouping@3a8624]" name="login" duration-ms="40" started-at="2017-07-25T22:56:43Z" finished-at="2017-07-25T22:56:43Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.info.TestRunner.Grouping.login(Grouping.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="search()[pri:2, instance:com.info.TestRunner.Grouping@3a8624]" name="search" duration-ms="14" started-at="2017-07-25T22:56:43Z" finished-at="2017-07-25T22:56:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method status="PASS" signature="advancedSearch()[pri:3, instance:com.info.TestRunner.Grouping@3a8624]" name="advancedSearch" duration-ms="8" started-at="2017-07-25T22:56:43Z" finished-at="2017-07-25T22:56:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- advancedSearch -->
        <test-method status="PASS" signature="billPayment()[pri:4, instance:com.info.TestRunner.Grouping@3a8624]" name="billPayment" duration-ms="2" started-at="2017-07-25T22:56:43Z" finished-at="2017-07-25T22:56:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- billPayment -->
        <test-method status="PASS" signature="prepaidRecharge()[pri:5, instance:com.info.TestRunner.Grouping@3a8624]" name="prepaidRecharge" duration-ms="4" started-at="2017-07-25T22:56:43Z" finished-at="2017-07-25T22:56:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepaidRecharge -->
        <test-method status="SKIP" signature="logout()[pri:10, instance:com.info.TestRunner.Grouping@3a8624]" name="logout" duration-ms="0" started-at="2017-07-25T22:56:43Z" depends-on-methods="com.info.TestRunner.Grouping.login" finished-at="2017-07-25T22:56:43Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Grouping.logout()[pri:10, instance:com.info.TestRunner.Grouping@3a8624] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Grouping.logout()[pri:10, instance:com.info.TestRunner.Grouping@3a8624] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.info.TestRunner.Grouping -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
